import { Config } from "./Config";
import { Policy } from "./Policy";
export declare function exists(file?: string): Promise<boolean>;
export declare function exampleConfig(): Config;
export declare function refresh(file?: string): Promise<Config>;
export declare function getConfig(file?: string): Promise<Config>;
export declare const writeConfig: (conf: Config, filePath?: string) => void;
export declare function savePolicy(name: string, policy: Policy): void;
export declare function deletePolicy(name: string): void;
export declare function setPolicyBaseline(name: string, count: number): void;
export declare function clear(): void;
